<?php

/**
 * @file
 * Initiate dev site.
 */

use Drupal\servicenow\Plugin\ServicenowUserLookup;

/**
 * Implements hook_install().
 */
function oit_dev_install() {
  $user_list = [
    'therealmeeseeks',
    'therealscaryterry',
    'therealbutterrobot',
    'therealjerry',
    'therealbeth',
    'therealmorty',
    'therealrick',
    'theRealSummer',
  ];
  $miles = user_load_by_name('france');
  new ServicenowUserLookup($miles);
  $affl = $miles->get('field_service_meow_affiliations')->getValue()[1]['value'];
  $dept = $miles->get('field_user_department')->getValue()[0]['value'];
  $uuid = $miles->get('field_service_meow_uuid')->getValue()[0]['value'];
  $sys_id = $miles->get('field_service_meow_sys_id')->getValue()[0]['value'];
  $dept_id = $miles->get('field_service_meow_department_id')->getValue()[0]['value'];
  $pod_group = $miles->get('field_service_meow_dds_pod_group')->getValue()[0]['value'];
  foreach ($user_list as $user) {
    $this_user = user_load_by_name($user);
    $this_user->set('field_user_name', $user);
    $this_user->set('field_service_meow_affiliations', $affl);
    $this_user->set('field_user_department', $dept);
    $this_user->set('field_service_meow_uuid', $uuid);
    $this_user->set('field_service_meow_sys_id', $sys_id);
    $this_user->set('field_service_meow_department_id', $dept_id);
    $this_user->set('field_service_meow_dds_pod_group', $pod_group);
    $this_user->save();
  }
  // Pull in archived news to add to add to robots.txt
  $news_archive = \Drupal::entityQuery('node');
  $news_archive->condition('field_news_archive', 3);
  $news_results = $news_archive->execute();
  $news_archive_string = "# Paths OIT\n";
  $news_archive_string .= "Disallow: /taxonomy/term/*\n";
  $news_archive_string .= "Disallow: /node?page=*\n";
  $news_archive_string .= "Disallow: /tutorial/hotmail-configure-outlook-windows?page=2\n";
  $news_archive_string .= "Disallow: /tutorial/hotmail-configure-outlook-windows?page=3\n";
  $news_archive_string .= "Disallow: /it-security/email-phishing/*\n";
  $news_archive_string .= "# Archived news nodes\n";
  foreach ($news_results as $news_result) {
    $news_archive_string .= "Disallow: /node/$news_result\n";
  }
  file_put_contents('../add-to-robots.txt', $news_archive_string);
}

/**
 * Implements hook_uninstall().
 */
function oit_dev_uninstall() {
  $file_pointer = "../add-to-robots.txt";
  // Remove add-to-robots.txt after usage.
  if (!unlink($file_pointer)) {
    echo ("$file_pointer cannot be deleted due to an error");
  } else {
    echo ("$file_pointer has been deleted");
  }
}
